import { defineConfig } from "vitest/config"

export default defineConfig({
  test: {
    coverage: {
      exclude: [
        "**/*.d.ts",
        "**/*.generated.*",
        "**/*.stories.*",
        "**/*.test.*",
        "**/*.spec.*",
        "**/index.ts",
        "**/test/**",
      ],
      include: [
        "apps/*/src/**/*.{ts,tsx}",
        "packages/*/src/**/*.{ts,tsx}",
        "packages/*/*/src/**/*.{ts,tsx}",
      ],
      provider: "v8",
      reporter: ["text", "json", "json-summary", "lcov"],
      reportsDirectory: "coverage",
      thresholds: {
        "**/auth/**/*.ts": {
          branches: 1,
          functions: 1,
          lines: 1,
          statements: 1,
        },
        "**/*repository*.ts": {
          branches: 1,
          functions: 1,
          lines: 1,
          statements: 1,
        },
        "**/migrations/**/*.ts": {
          branches: 1,
          functions: 1,
          lines: 1,
          statements: 1,
        },
        "**/*sync*.ts": {
          branches: 1,
          functions: 1,
          lines: 1,
          statements: 1,
        },
      },
    },
    projects: [
      "apps/admin/vitest.config.ts",
      "apps/api/vitest.config.ts",
      "apps/web/vitest.config.ts",
      "packages/infra/ai/vitest.config.ts",
      "packages/infra/auth/vitest.config.ts",
      "packages/shared/contracts/vitest.config.ts",
      "packages/core/vitest.config.ts",
      "packages/infra/db/vitest.config.ts",
      "packages/infra/event-bus/vitest.config.ts",
      "packages/config/env/vitest.config.ts",
      "packages/infra/http-client/vitest.config.ts",
      "packages/infra/http-platform/vitest.config.ts",
      "packages/modules/ai-feedback/vitest.config.ts",
      "packages/modules/content/vitest.config.ts",
      "packages/modules/identity/vitest.config.ts",
      "packages/modules/learning/vitest.config.ts",
      "packages/modules/resource-library/vitest.config.ts",
      "packages/infra/observability/vitest.config.ts",
      "packages/infra/storage/vitest.config.ts",
      "packages/shared/errors/vitest.config.ts",
      "packages/shared/resource-document/vitest.config.ts",
      "packages/shared/ui/vitest.config.ts",
    ],
  },
})
