/** docs/product/lesson-step-templates.md에서 생성. 수동 편집하지 마세요. */
import { z } from "zod"

export const lessonTemplateKindValues = [
  "Cg",
  "Cp",
  "EC",
  "FB",
  "MC",
  "Mt",
  "Or",
  "Rd",
  "SB",
  "Sl",
  "TF",
] as const

export const lessonTemplateIdValues = [
  "A1",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "B1",
  "B2",
  "B3",
  "B4",
  "B5",
  "B6",
  "B7",
  "C1",
  "C2",
  "C3",
  "C4",
  "C5",
  "C6",
  "D1",
  "D2",
  "D3",
  "D4",
  "D5",
  "D6",
  "D7",
  "D8",
  "E1",
  "E2",
  "E3",
  "E4",
  "E5",
  "E6",
  "E7",
  "E8",
  "E9",
  "F1",
  "F2",
  "F3",
  "F4",
  "F5",
  "G1",
  "G2",
  "G3",
  "G4",
  "G5",
  "G6",
  "H1",
  "H2",
  "H3",
  "H4",
  "H5",
  "I1",
  "I2",
  "I3",
  "I4",
  "I5",
  "I6",
] as const

export const lessonTemplateKindSchema = z.enum(lessonTemplateKindValues)
export const lessonTemplateIdSchema = z.enum(lessonTemplateIdValues)

export type LessonTemplateKind = z.infer<typeof lessonTemplateKindSchema>
export type LessonTemplateId = z.infer<typeof lessonTemplateIdSchema>

export type LessonTemplate = Readonly<{
  closing: LessonTemplateKind
  layout: readonly LessonTemplateKind[]
  stepCount: number
}>

export const lessonTemplates = {
  A1: {
    closing: "Sl",
    layout: ["TF", "Cp", "MC", "Mt", "Sl", "FB", "TF", "Cg", "Mt", "EC", "Sl"],
    stepCount: 11,
  },
  A2: {
    closing: "Cg",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Cg",
      "Sl",
      "Cg",
      "TF",
      "MC",
      "Cg",
      "Sl",
      "EC",
      "Cg",
    ],
    stepCount: 12,
  },
  A3: {
    closing: "SB",
    layout: [
      "Sl",
      "TF",
      "MC",
      "Cg",
      "FB",
      "Sl",
      "TF",
      "Cg",
      "FB",
      "Sl",
      "EC",
      "SB",
    ],
    stepCount: 12,
  },
  A4: {
    closing: "FB",
    layout: ["TF", "FB", "MC", "FB", "Sl", "FB", "EC", "FB", "SB", "FB"],
    stepCount: 10,
  },
  A5: {
    closing: "MC",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Mt",
      "FB",
      "Sl",
      "TF",
      "Mt",
      "Cg",
      "FB",
      "EC",
      "MC",
    ],
    stepCount: 12,
  },
  A6: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Sl", "Cp", "Sl", "TF", "Cg", "EC", "Sl"],
    stepCount: 10,
  },
  A7: {
    closing: "Sl",
    layout: [
      "Sl",
      "TF",
      "MC",
      "Sl",
      "EC",
      "Sl",
      "TF",
      "Cg",
      "Sl",
      "EC",
      "FB",
      "EC",
      "Sl",
    ],
    stepCount: 13,
  },
  A8: {
    closing: "FB",
    layout: [
      "TF",
      "MC",
      "Mt",
      "FB",
      "Cg",
      "TF",
      "Mt",
      "FB",
      "Sl",
      "Cg",
      "EC",
      "FB",
    ],
    stepCount: 12,
  },
  B1: {
    closing: "SB",
    layout: [
      "Sl",
      "TF",
      "MC",
      "EC",
      "Sl",
      "MC",
      "TF",
      "EC",
      "Sl",
      "FB",
      "EC",
      "SB",
    ],
    stepCount: 12,
  },
  B2: {
    closing: "SB",
    layout: ["SB", "MC", "SB", "Sl", "SB", "TF", "Or", "SB", "FB", "SB", "SB"],
    stepCount: 11,
  },
  B3: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Cg",
      "Sl",
      "Cp",
      "TF",
      "Cg",
      "Sl",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  B4: {
    closing: "Sl",
    layout: ["Sl", "TF", "MC", "Sl", "EC", "Sl", "TF", "Cp", "Sl", "EC", "Sl"],
    stepCount: 11,
  },
  B5: {
    closing: "EC",
    layout: [
      "TF",
      "MC",
      "Sl",
      "Cg",
      "TF",
      "Sl",
      "MC",
      "Cg",
      "Sl",
      "EC",
      "FB",
      "EC",
    ],
    stepCount: 12,
  },
  B6: {
    closing: "SB",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "FB",
      "TF",
      "Sl",
      "EC",
      "FB",
      "Sl",
      "EC",
      "SB",
    ],
    stepCount: 12,
  },
  B7: {
    closing: "SB",
    layout: ["Cp", "TF", "MC", "Sl", "SB", "Cp", "TF", "Or", "SB", "EC", "SB"],
    stepCount: 11,
  },
  C1: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "Or",
      "Cg",
      "TF",
      "Or",
      "Sl",
      "Cg",
      "Or",
      "Sl",
    ],
    stepCount: 12,
  },
  C2: {
    closing: "FB",
    layout: ["TF", "MC", "Sl", "FB", "MC", "Sl", "TF", "Mt", "FB", "Sl", "FB"],
    stepCount: 11,
  },
  C3: {
    closing: "FB",
    layout: [
      "TF",
      "MC",
      "Mt",
      "TF",
      "FB",
      "Mt",
      "Sl",
      "TF",
      "FB",
      "Mt",
      "EC",
      "FB",
    ],
    stepCount: 12,
  },
  C4: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "Cg",
      "TF",
      "Sl",
      "Cg",
      "Sl",
      "EC",
      "FB",
      "Sl",
    ],
    stepCount: 12,
  },
  C5: {
    closing: "SB",
    layout: ["Cp", "TF", "MC", "Or", "FB", "Sl", "TF", "Or", "FB", "EC", "SB"],
    stepCount: 11,
  },
  C6: {
    closing: "SB",
    layout: ["TF", "MC", "SB", "Or", "TF", "FB", "SB", "Or", "EC", "SB"],
    stepCount: 10,
  },
  D1: {
    closing: "MC",
    layout: [
      "TF",
      "MC",
      "Cg",
      "Sl",
      "MC",
      "TF",
      "Cg",
      "Sl",
      "EC",
      "Sl",
      "Cg",
      "MC",
    ],
    stepCount: 12,
  },
  D2: {
    closing: "Sl",
    layout: ["Sl", "TF", "MC", "Sl", "Cg", "TF", "Sl", "Cg", "EC", "Sl"],
    stepCount: 10,
  },
  D3: {
    closing: "SB",
    layout: ["Cp", "TF", "MC", "Or", "FB", "TF", "Or", "Sl", "EC", "Or", "SB"],
    stepCount: 11,
  },
  D4: {
    closing: "MC",
    layout: [
      "TF",
      "MC",
      "Cg",
      "Mt",
      "Sl",
      "TF",
      "Cg",
      "Mt",
      "Sl",
      "Cg",
      "FB",
      "MC",
    ],
    stepCount: 12,
  },
  D5: {
    closing: "SB",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Or",
      "Cg",
      "TF",
      "Or",
      "FB",
      "Sl",
      "Cg",
      "Or",
      "SB",
    ],
    stepCount: 12,
  },
  D6: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Sl", "FB", "TF", "Cp", "Sl", "FB", "EC", "Sl"],
    stepCount: 11,
  },
  D7: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Sl", "Cp", "TF", "Mt", "Sl", "EC", "Sl"],
    stepCount: 10,
  },
  D8: {
    closing: "Sl",
    layout: ["Sl", "TF", "MC", "FB", "Cg", "TF", "FB", "Sl", "EC", "FB", "Sl"],
    stepCount: 11,
  },
  E1: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Cg",
      "Sl",
      "TF",
      "Cg",
      "Sl",
      "FB",
      "Cg",
      "EC",
      "Sl",
    ],
    stepCount: 12,
  },
  E2: {
    closing: "MC",
    layout: ["TF", "MC", "Mt", "Cg", "Sl", "TF", "Mt", "Cg", "Sl", "EC", "MC"],
    stepCount: 11,
  },
  E3: {
    closing: "MC",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Cg",
      "TF",
      "Sl",
      "Cg",
      "Mt",
      "Sl",
      "Cg",
      "EC",
      "MC",
    ],
    stepCount: 12,
  },
  E4: {
    closing: "SB",
    layout: [
      "TF",
      "MC",
      "Mt",
      "Or",
      "Cg",
      "TF",
      "Or",
      "FB",
      "Sl",
      "Cg",
      "Or",
      "EC",
      "SB",
    ],
    stepCount: 13,
  },
  E5: {
    closing: "MC",
    layout: ["TF", "MC", "Cg", "TF", "Cg", "Sl", "TF", "Cg", "Sl", "Cg", "MC"],
    stepCount: 11,
  },
  E6: {
    closing: "SB",
    layout: [
      "TF",
      "MC",
      "FB",
      "Or",
      "TF",
      "Mt",
      "FB",
      "Sl",
      "Or",
      "EC",
      "FB",
      "SB",
    ],
    stepCount: 12,
  },
  E7: {
    closing: "Sl",
    layout: [
      "TF",
      "MC",
      "Cg",
      "Sl",
      "TF",
      "Mt",
      "Cg",
      "Sl",
      "TF",
      "Cg",
      "EC",
      "Sl",
    ],
    stepCount: 12,
  },
  E8: {
    closing: "MC",
    layout: [
      "TF",
      "MC",
      "Mt",
      "Cg",
      "Sl",
      "TF",
      "Mt",
      "Cg",
      "Sl",
      "EC",
      "Sl",
      "Cg",
      "MC",
    ],
    stepCount: 13,
  },
  E9: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "FB",
      "TF",
      "Cp",
      "Sl",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  F1: {
    closing: "Sl",
    layout: ["TF", "MC", "Cg", "Sl", "Cp", "TF", "Cg", "Sl", "EC", "Sl"],
    stepCount: 10,
  },
  F2: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "Or",
      "TF",
      "Mt",
      "Sl",
      "Or",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  F3: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Mt", "Cg", "TF", "Sl", "Cg", "Sl", "EC", "Sl"],
    stepCount: 11,
  },
  F4: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Cg", "TF", "Sl", "Cp", "Sl", "EC", "SB", "Sl"],
    stepCount: 11,
  },
  F5: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Or",
      "FB",
      "TF",
      "Or",
      "Sl",
      "EC",
      "Or",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  G1: {
    closing: "Sl",
    layout: ["Sl", "TF", "MC", "Sl", "Cg", "TF", "Sl", "Cg", "Sl", "EC", "Sl"],
    stepCount: 11,
  },
  G2: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "FB",
      "TF",
      "Or",
      "Sl",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  G3: {
    closing: "Cg",
    layout: [
      "TF",
      "MC",
      "Cg",
      "Sl",
      "TF",
      "Cg",
      "Sl",
      "TF",
      "Cg",
      "Sl",
      "EC",
      "Cg",
    ],
    stepCount: 12,
  },
  G4: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Cg", "Sl", "TF", "Cp", "Sl", "Cg", "EC", "Sl"],
    stepCount: 11,
  },
  G5: {
    closing: "Sl",
    layout: [
      "Sl",
      "TF",
      "MC",
      "Cg",
      "Sl",
      "TF",
      "Mt",
      "Sl",
      "EC",
      "Sl",
      "FB",
      "EC",
      "Sl",
    ],
    stepCount: 13,
  },
  G6: {
    closing: "MC",
    layout: ["TF", "MC", "Or", "Mt", "TF", "Cg", "Or", "Sl", "Cg", "Or", "MC"],
    stepCount: 11,
  },
  H1: {
    closing: "Sl",
    layout: ["Cp", "TF", "MC", "Sl", "Or", "TF", "FB", "Sl", "EC", "SB", "Sl"],
    stepCount: 11,
  },
  H2: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Cg",
      "Or",
      "TF",
      "Sl",
      "Or",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  H3: {
    closing: "Sl",
    layout: [
      "TF",
      "MC",
      "Mt",
      "FB",
      "TF",
      "Or",
      "SB",
      "Sl",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  H4: {
    closing: "MC",
    layout: ["TF", "MC", "Cg", "Sl", "TF", "Cg", "Sl", "TF", "Cg", "EC", "MC"],
    stepCount: 11,
  },
  H5: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "FB",
      "TF",
      "Mt",
      "Sl",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 12,
  },
  I1: {
    closing: "Sl",
    layout: [
      "TF",
      "MC",
      "Mt",
      "Cg",
      "Sl",
      "TF",
      "Or",
      "Cg",
      "Sl",
      "EC",
      "FB",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 14,
  },
  I2: {
    closing: "Sl",
    layout: [
      "TF",
      "MC",
      "Cg",
      "Or",
      "TF",
      "Sl",
      "Cg",
      "Or",
      "Sl",
      "EC",
      "FB",
      "Or",
      "Sl",
    ],
    stepCount: 13,
  },
  I3: {
    closing: "Sl",
    layout: [
      "TF",
      "MC",
      "Mt",
      "Sl",
      "TF",
      "Cg",
      "Mt",
      "Sl",
      "EC",
      "FB",
      "EC",
      "Sl",
    ],
    stepCount: 12,
  },
  I4: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "Cp",
      "TF",
      "Cg",
      "Sl",
      "EC",
      "Cp",
      "EC",
      "Sl",
    ],
    stepCount: 12,
  },
  I5: {
    closing: "Sl",
    layout: [
      "Sl",
      "TF",
      "MC",
      "Sl",
      "EC",
      "Cg",
      "TF",
      "Sl",
      "EC",
      "FB",
      "Sl",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 14,
  },
  I6: {
    closing: "Sl",
    layout: [
      "Cp",
      "TF",
      "MC",
      "Sl",
      "Cg",
      "TF",
      "Or",
      "Mt",
      "Sl",
      "FB",
      "EC",
      "Sl",
      "EC",
      "SB",
      "Sl",
    ],
    stepCount: 15,
  },
} as const satisfies Record<LessonTemplateId, LessonTemplate>

export function getLessonTemplate(
  templateId: LessonTemplateId
): LessonTemplate {
  return lessonTemplates[templateId]
}
