/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=ApiBindings src/worker-configuration.d.ts` (hash: 5780f7b54b93fa4ef5fd76ed3876a4e1)
interface __BaseEnv_ApiBindings {
	CONTENT_ASSETS: R2Bucket;
	PRIVATE_DATA: R2Bucket;
	DB: D1Database;
	EMAIL?: SendEmail;
	AI?: Ai;
	IMAGES: ImagesBinding;
	WEB_ORIGIN: string;
	ADMIN_ORIGIN: string;
	NODE_ENV: string;
	DEPLOYMENT_ENVIRONMENT: string;
	DEPLOYMENT_VERSION: string;
	LOG_LEVEL: string;
	LEARNER_AUTH_SECRET: string;
	ADMIN_AUTH_SECRET: string;
	CURSOR_SIGNING_SECRET: string;
	GOOGLE_CLIENT_ID?: string;
	GOOGLE_CLIENT_SECRET?: string;
	AUTH_EMAIL_FROM?: string;
	LOCAL_MAILBOX?: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface StagingEnv {
		CONTENT_ASSETS: R2Bucket;
		PRIVATE_DATA: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		AI: Ai;
		IMAGES: ImagesBinding;
		WEB_ORIGIN: string;
		ADMIN_ORIGIN: string;
		NODE_ENV: string;
		DEPLOYMENT_ENVIRONMENT: string;
		DEPLOYMENT_VERSION: string;
		LOG_LEVEL: string;
		LEARNER_AUTH_SECRET: string;
		ADMIN_AUTH_SECRET: string;
		CURSOR_SIGNING_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		AUTH_EMAIL_FROM: string;
	}
	interface ProductionEnv {
		CONTENT_ASSETS: R2Bucket;
		PRIVATE_DATA: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		AI: Ai;
		IMAGES: ImagesBinding;
		WEB_ORIGIN: string;
		ADMIN_ORIGIN: string;
		NODE_ENV: string;
		DEPLOYMENT_ENVIRONMENT: string;
		DEPLOYMENT_VERSION: string;
		LOG_LEVEL: string;
		LEARNER_AUTH_SECRET: string;
		ADMIN_AUTH_SECRET: string;
		CURSOR_SIGNING_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		AUTH_EMAIL_FROM: string;
	}
	interface Env extends __BaseEnv_ApiBindings {}
}
interface ApiBindings extends __BaseEnv_ApiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_ORIGIN" | "ADMIN_ORIGIN" | "NODE_ENV" | "DEPLOYMENT_ENVIRONMENT" | "DEPLOYMENT_VERSION" | "LOG_LEVEL" | "LEARNER_AUTH_SECRET" | "ADMIN_AUTH_SECRET" | "CURSOR_SIGNING_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "AUTH_EMAIL_FROM">> {}
}
