import type {
  WritingDifficulty,
  WritingDomain,
} from "@workspace/contracts/writing/writing"

type SeedWritingTask = {
  audience: string
  difficulty: WritingDifficulty
  domain: WritingDomain
  goalChars: number
  id: string
  minChars: number
  requiredElements: readonly string[]
  situation: string
  taskId: string
  title: string
  typeName: string
}

export const defaultWritingTaskSeed: readonly SeedWritingTask[] = [
  {
    audience: "친구",
    difficulty: "입문",
    domain: "일상·실용문",
    goalChars: 120,
    id: "p-invite",
    minChars: 60,
    requiredElements: [
      "언제·어디서 만나는지 밝힌다",
      "상대가 답할 수 있게 한 질문을 남긴다",
    ],
    situation:
      "주말에 가까운 사람을 공원 소풍에 초대하는 짧은 메시지를 씁니다.",
    taskId: "t-invite",
    title: "주말 소풍 초대 메시지",
    typeName: "초대장",
  },
  {
    audience: "처음 오는 손님",
    difficulty: "기본",
    domain: "일상·실용문",
    goalChars: 200,
    id: "p-review",
    minChars: 100,
    requiredElements: [
      "먹은 메뉴를 구체적으로 적는다",
      "다시 갈지 여부를 분명히 한다",
    ],
    situation: "어제 간 식당을 다른 손님이 고를 수 있게 후기를 남깁니다.",
    taskId: "t-review",
    title: "동네 식당 후기",
    typeName: "후기",
  },
  {
    audience: "같은 수업 동료",
    difficulty: "기본",
    domain: "학업·논술문",
    goalChars: 250,
    id: "p-summary",
    minChars: 120,
    requiredElements: [
      "기사의 주장을 한 문장으로 남긴다",
      "근거를 두 가지 이상 정리한다",
    ],
    situation: "제공된 기사의 주장과 근거만 남기고 짧게 정리합니다.",
    taskId: "t-summary",
    title: "기사 한 편의 핵심 요약",
    typeName: "요약문",
  },
  {
    audience: "함께 일하는 팀",
    difficulty: "입문",
    domain: "업무·비즈니스 문서",
    goalChars: 180,
    id: "p-email",
    minChars: 80,
    requiredElements: [
      "변경된 일시를 분명히 적는다",
      "양해와 다음 행동을 한 문장씩 넣는다",
    ],
    situation: "내일 회의를 이틀 뒤로 미루는 이유를 정중하게 알립니다.",
    taskId: "t-email",
    title: "회의 일정 변경 안내",
    typeName: "이메일",
  },
  {
    audience: "글 읽는 낯선 사람",
    difficulty: "심화",
    domain: "창작·문학",
    goalChars: 400,
    id: "p-essay",
    minChars: 200,
    requiredElements: [
      "한 장면을 감각으로 묘사한다",
      "그날의 감정을 직접 이름 붙인다",
    ],
    situation: "오늘 아침의 한 장면을 짧은 수필로 옮깁니다.",
    taskId: "t-essay",
    title: "비 오는 출근길",
    typeName: "수필",
  },
  {
    audience: "학교 신문 독자",
    difficulty: "심화",
    domain: "설득·의견문",
    goalChars: 500,
    id: "p-column",
    minChars: 200,
    requiredElements: [
      "한 문단 안에 주장과 근거를 연결한다",
      "반대 의견을 한 문장 이상 다룬다",
      "격식체를 유지한다",
    ],
    situation: "숙제를 줄이자는 주장과 근거, 예상 반론을 한 칼럼으로 씁니다.",
    taskId: "t-column",
    title: "숙제 폐지 찬반 칼럼",
    typeName: "칼럼",
  },
  {
    audience: "비개발 동료",
    difficulty: "기본",
    domain: "정보전달·설명문",
    goalChars: 300,
    id: "p-explain",
    minChars: 150,
    requiredElements: [
      "두 개념을 각각 한 문장으로 정의한다",
      "차이를 한 가지 쓰임으로 비교한다",
    ],
    situation:
      "기술 지식이 없는 동료에게 두 개념의 차이를 순서대로 설명합니다.",
    taskId: "t-explain",
    title: "캐시와 쿠키 차이 설명",
    typeName: "개념 설명",
  },
  {
    audience: "채용 담당자",
    difficulty: "기본",
    domain: "자기서사·기록",
    goalChars: 400,
    id: "p-intro",
    minChars: 180,
    requiredElements: [
      "지원하는 일과 내 경험을 연결한다",
      "그 일이 하고 싶은 이유를 한 문장으로 밝힌다",
    ],
    situation: "지원하는 일과 내 경험을 한 문단에서 연결합니다.",
    taskId: "t-intro",
    title: "지원 동기 한 문단",
    typeName: "자기소개서",
  },
  {
    audience: "동료",
    difficulty: "입문",
    domain: "관계·소통 문서",
    goalChars: 160,
    id: "p-thanks",
    minChars: 70,
    requiredElements: [
      "어떤 도움이었는지 구체적으로 적는다",
      "고마운 마음을 직접 표현한다",
    ],
    situation: "바쁜 일정 중에 일을 나눠 준 동료에게 짧게 감사를 전합니다.",
    taskId: "t-thanks",
    title: "도움을 준 동료에게 감사",
    typeName: "감사편지",
  },
  {
    audience: "블로그 독자",
    difficulty: "기본",
    domain: "디지털·뉴미디어",
    goalChars: 350,
    id: "p-blog",
    minChars: 160,
    requiredElements: [
      "코스의 시작과 끝을 안내한다",
      "그 길을 권하는 이유를 한 가지 이상 적는다",
    ],
    situation: "독자가 따라 걸을 수 있게 코스와 이유를 소개합니다.",
    taskId: "t-blog",
    title: "주말 산책 코스 소개",
    typeName: "블로그 포스트",
  },
  {
    audience: "택배 기사님",
    difficulty: "입문",
    domain: "일상·실용문",
    goalChars: 130,
    id: "p-lost-parcel",
    minChars: 60,
    requiredElements: [
      "주문한 물건과 배송 상태를 구체적으로 밝힌다",
      "확인을 부탁하는 말을 정중하게 남긴다",
    ],
    situation:
      "주문한 물건이 배송완료로 표시되었지만 집에 도착하지 않아, 택배 기사님께 상황을 확인하는 메시지를 보냅니다.",
    taskId: "t-lost-parcel",
    title: "택배 분실 문의 메시지",
    typeName: "문의 메시지",
  },
  {
    audience: "아래층 이웃",
    difficulty: "기본",
    domain: "일상·실용문",
    goalChars: 220,
    id: "p-noise-note",
    minChars: 100,
    requiredElements: [
      "불편을 끼친 상황을 구체적으로 언급하며 사과한다",
      "앞으로 개선할 행동을 한 가지 이상 제시한다",
      "직접 대화할 수 있는 여지를 남긴다",
    ],
    situation:
      "아이가 뛰어노는 소리로 아래층에 불편을 끼친 것 같아, 사과와 함께 앞으로의 노력을 담은 쪽지를 문 앞에 남깁니다.",
    taskId: "t-noise-note",
    title: "층간소음에 대한 사과와 양해 쪽지",
    typeName: "안내 쪽지",
  },
  {
    audience: "같은 반 친구들",
    difficulty: "기본",
    domain: "학업·논술문",
    goalChars: 280,
    id: "p-book-report",
    minChars: 140,
    requiredElements: [
      "책의 줄거리를 세 문장 이내로 요약한다",
      "인상 깊었던 장면이나 문장을 한 가지 밝힌다",
      "책을 읽고 달라진 생각을 적는다",
    ],
    situation:
      "최근에 읽은 책 한 권을 골라 줄거리와 자신의 생각을 반 친구들에게 소개하는 글을 씁니다.",
    taskId: "t-book-report",
    title: "인상 깊은 책 한 권 소개",
    typeName: "독서 감상문",
  },
  {
    audience: "논술 시험 채점자",
    difficulty: "심화",
    domain: "학업·논술문",
    goalChars: 550,
    id: "p-uniform-debate",
    minChars: 220,
    requiredElements: [
      "서론에서 자신의 입장을 명확히 밝힌다",
      "근거를 두 가지 이상 제시하고 각각에 예를 든다",
      "반대 입장을 한 문장 이상 언급하고 반박한다",
      "결론에서 주장을 다시 정리한다",
    ],
    situation:
      "교복 자율화에 찬성하는지 반대하는지 입장을 정하고, 근거를 들어 논리적으로 주장하는 글을 씁니다.",
    taskId: "t-uniform-debate",
    title: "교복 자율화 찬반 논술",
    typeName: "논설문",
  },
  {
    audience: "동아리 부원 전체",
    difficulty: "기본",
    domain: "업무·비즈니스 문서",
    goalChars: 260,
    id: "p-club-minutes",
    minChars: 130,
    requiredElements: [
      "회의 일시와 참석자를 밝힌다",
      "논의된 안건과 결정 사항을 구분해서 정리한다",
      "다음 회의까지 해야 할 일을 담당자별로 명시한다",
    ],
    situation:
      "오늘 열린 동아리 정기 회의에서 논의된 안건과 결정 사항을 정리해 부원들에게 공유합니다.",
    taskId: "t-club-minutes",
    title: "동아리 정기 회의록",
    typeName: "회의록",
  },
  {
    audience: "학생회 담당 선생님",
    difficulty: "심화",
    domain: "업무·비즈니스 문서",
    goalChars: 480,
    id: "p-event-proposal",
    minChars: 200,
    requiredElements: [
      "행사의 목적과 기대 효과를 밝힌다",
      "진행 일정과 필요한 자원을 구체적으로 적는다",
      "예상되는 문제와 대응 방안을 한 가지 이상 제시한다",
    ],
    situation:
      "학교에서 열고 싶은 행사를 하나 정해 목적과 진행 방식을 담은 기획안을 작성하고 담당 선생님께 승인을 요청합니다.",
    taskId: "t-event-proposal",
    title: "교내 행사 기획안",
    typeName: "기획안",
  },
  {
    audience: "나만의 오래된 물건",
    difficulty: "입문",
    domain: "창작·문학",
    goalChars: 160,
    id: "p-letter-to-object",
    minChars: 70,
    requiredElements: [
      "물건과 함께한 순간을 하나 구체적으로 떠올린다",
      "그 물건에게 하고 싶은 말을 직접 건넨다",
    ],
    situation:
      "오랫동안 곁에 있었던 물건 하나를 정해, 그 물건에게 마음을 전하는 짧은 편지를 씁니다.",
    taskId: "t-letter-to-object",
    title: "오래된 물건에게 쓰는 편지",
    typeName: "편지글",
  },
  {
    audience: "글쓰기 합평 모임",
    difficulty: "심화",
    domain: "창작·문학",
    goalChars: 500,
    id: "p-fiction-scene",
    minChars: 230,
    requiredElements: [
      "인물 간의 갈등이 대화를 통해 드러나게 한다",
      "인물의 감정을 행동이나 표정으로 보여준다",
      "장면의 배경을 감각적으로 묘사한다",
    ],
    situation:
      "두 인물 사이에 갈등이 생기는 순간을 하나 상상해, 대화와 행동으로 그 장면을 그려냅니다.",
    taskId: "t-fiction-scene",
    title: "갈등이 드러나는 짧은 장면",
    typeName: "짧은 소설",
  },
  {
    audience: "학교 행정실",
    difficulty: "기본",
    domain: "설득·의견문",
    goalChars: 240,
    id: "p-water-purifier",
    minChars: 110,
    requiredElements: [
      "현재 겪고 있는 불편을 구체적인 상황으로 설명한다",
      "건의하는 내용을 명확한 문장으로 제시한다",
      "건의가 받아들여졌을 때의 효과를 밝힌다",
    ],
    situation:
      "쉬는 시간마다 정수기 앞에 줄이 길게 늘어서는 불편을 해결하기 위해, 정수기 추가 설치를 건의하는 글을 씁니다.",
    taskId: "t-water-purifier",
    title: "교내 정수기 추가 설치 건의문",
    typeName: "건의문",
  },
  {
    audience: "지역 신문 독자",
    difficulty: "심화",
    domain: "설득·의견문",
    goalChars: 550,
    id: "p-plastic-ban",
    minChars: 220,
    requiredElements: [
      "한 문단 안에서 주장과 근거를 긴밀하게 연결한다",
      "통계나 사례를 근거로 한 가지 이상 활용한다",
      "반대 의견을 한 문장 이상 소개하고 재반박한다",
      "격식체를 끝까지 유지한다",
    ],
    situation:
      "일회용 플라스틱 사용을 법으로 규제하는 것에 대한 자신의 입장을 정해, 지역 신문에 실릴 논설문을 씁니다.",
    taskId: "t-plastic-ban",
    title: "일회용 플라스틱 규제 찬반 논설문",
    typeName: "논설문",
  },
  {
    audience: "처음 써 보는 사람",
    difficulty: "입문",
    domain: "정보전달·설명문",
    goalChars: 150,
    id: "p-umbrella-guide",
    minChars: 60,
    requiredElements: [
      "순서를 나타내는 말을 사용해 단계별로 적는다",
      "주의할 점을 한 가지 이상 알려준다",
    ],
    situation:
      "자동으로 펴고 접는 우산을 처음 쓰는 사람이 이해할 수 있도록, 우산을 접는 순서를 설명합니다.",
    taskId: "t-umbrella-guide",
    title: "자동우산 접는 법 설명",
    typeName: "사용법 설명문",
  },
  {
    audience: "학생증을 분실한 신입생",
    difficulty: "심화",
    domain: "정보전달·설명문",
    goalChars: 420,
    id: "p-id-reissue",
    minChars: 200,
    requiredElements: [
      "신청에 필요한 준비물을 빠짐없이 안내한다",
      "절차를 순서대로 번호를 매겨 정리한다",
      "자주 발생하는 실수나 유의 사항을 알려준다",
    ],
    situation:
      "학생증을 잃어버린 신입생이 절차대로 따라 할 수 있도록, 재발급 신청 과정을 순서대로 안내합니다.",
    taskId: "t-id-reissue",
    title: "학생증 재발급 신청 절차 안내",
    typeName: "절차 안내문",
  },
  {
    audience: "나 자신",
    difficulty: "입문",
    domain: "자기서사·기록",
    goalChars: 140,
    id: "p-daily-diary",
    minChars: 60,
    requiredElements: [
      "오늘 있었던 일을 구체적인 장면으로 적는다",
      "그때 느낀 감정을 직접 표현한다",
    ],
    situation:
      "오늘 있었던 일 중 기억에 남는 순간을 하나 골라 짧은 일기로 남깁니다.",
    taskId: "t-daily-diary",
    title: "오늘 하루 돌아보기",
    typeName: "일기",
  },
  {
    audience: "미래의 나",
    difficulty: "기본",
    domain: "자기서사·기록",
    goalChars: 260,
    id: "p-turning-point",
    minChars: 130,
    requiredElements: [
      "그 순간에 있었던 일을 시간 순서로 설명한다",
      "그 일이 지금의 나에게 미친 영향을 밝힌다",
    ],
    situation:
      "지금까지 살면서 나를 바꾼 순간을 하나 골라, 그 일이 어떤 의미였는지 돌아보는 글을 씁니다.",
    taskId: "t-turning-point",
    title: "나를 바꾼 순간",
    typeName: "자기 기록 에세이",
  },
  {
    audience: "친한 친구",
    difficulty: "입문",
    domain: "관계·소통 문서",
    goalChars: 140,
    id: "p-apology-friend",
    minChars: 60,
    requiredElements: [
      "무엇을 잘못했는지 구체적으로 밝힌다",
      "다음에 어떻게 하겠다는 약속을 남긴다",
    ],
    situation:
      "친구와의 약속을 깜빡 잊고 나가지 못한 일에 대해 사과하는 메시지를 보냅니다.",
    taskId: "t-apology-friend",
    title: "약속을 어긴 친구에게 사과",
    typeName: "사과 편지",
  },
  {
    audience: "대학에 합격한 친구",
    difficulty: "기본",
    domain: "관계·소통 문서",
    goalChars: 220,
    id: "p-congrats-card",
    minChars: 100,
    requiredElements: [
      "친구가 노력해 온 과정을 구체적으로 언급한다",
      "축하하는 마음을 직접 표현한다",
      "앞으로를 응원하는 말을 남긴다",
    ],
    situation:
      "오랫동안 준비해 온 친구가 원하는 대학에 합격했다는 소식을 듣고, 축하하는 마음을 담은 카드를 씁니다.",
    taskId: "t-congrats-card",
    title: "합격한 친구에게 보내는 축하 카드",
    typeName: "축하 카드",
  },
  {
    audience: "시청 도로관리과 담당자",
    difficulty: "기본",
    domain: "공적·행정 문서",
    goalChars: 240,
    id: "p-road-report",
    minChars: 110,
    requiredElements: [
      "파손 위치를 다른 사람도 찾을 수 있게 구체적으로 밝힌다",
      "파손 상태와 위험성을 사실대로 설명한다",
      "요청하는 조치를 분명한 문장으로 적는다",
    ],
    situation:
      "등굣길에 발견한 도로 파손 지점을 시청에 신고해 보수를 요청하는 민원을 씁니다.",
    taskId: "t-road-report",
    title: "도로 파손 민원 신청",
    typeName: "민원 신청서",
  },
  {
    audience: "학과 행정실",
    difficulty: "심화",
    domain: "공적·행정 문서",
    goalChars: 380,
    id: "p-leave-request",
    minChars: 180,
    requiredElements: [
      "휴학이 필요한 사유를 정중하고 명확하게 밝힌다",
      "휴학 기간과 복학 예정 시기를 구체적으로 적는다",
      "격식체와 정중한 어휘를 끝까지 유지한다",
    ],
    situation:
      "개인 사정으로 한 학기 휴학을 하려고 하며, 신청서에 들어갈 휴학 사유를 격식에 맞게 작성합니다.",
    taskId: "t-leave-request",
    title: "휴학 신청서 사유 작성",
    typeName: "신청서",
  },
  {
    audience: "SNS 팔로워",
    difficulty: "입문",
    domain: "디지털·뉴미디어",
    goalChars: 120,
    id: "p-travel-post",
    minChars: 50,
    requiredElements: [
      "사진 속 장소나 순간을 짧게 설명한다",
      "그때의 느낌을 담은 표현을 넣는다",
    ],
    situation:
      "여행에서 찍은 사진 한 장을 SNS에 올리며, 사진과 어울리는 짧은 설명 글을 함께 씁니다.",
    taskId: "t-travel-post",
    title: "여행 사진 SNS 게시글",
    typeName: "SNS 게시물",
  },
  {
    audience: "커뮤니티 회원들",
    difficulty: "기본",
    domain: "디지털·뉴미디어",
    goalChars: 240,
    id: "p-laptop-question",
    minChars: 110,
    requiredElements: [
      "궁금한 점을 구체적인 질문으로 정리한다",
      "자신의 상황과 조건을 배경 정보로 제시한다",
      "답변자가 참고할 정보를 충분히 제공한다",
    ],
    situation:
      "노트북 구매를 고민하고 있어, 다른 사람들의 조언을 얻기 위해 커뮤니티에 질문 글을 올립니다.",
    taskId: "t-laptop-question",
    title: "노트북 구매 조언을 구하는 글",
    typeName: "질문 게시글",
  },
]
